### ISSUE TITLE
Kernel died before replying to kernel_info

### ISSUE THREAD

**Issue by librarianmage** [joouha/euporie#75] opened 2023-05-23 20:43 UTC
Every time I try using the python kernel, it fails with the above RuntimeError.

If it is relevant, I have installed euporie using pipx and the dev branch.

**Comment by librarianmage** [comment] 2023-05-23 20:46
The sage kernel, by comparison, has always worked

**Comment by JustinStitt** [comment] 2023-05-24 00:43
I am having the same issue.

**Comment by JustinStitt** [comment] 2023-05-24 00:44
@librarianmage Resolved with `$ pip install ipykernel`

**Comment by joouha** [comment] 2023-05-24 08:09
[This closed issue](https://github.com/joouha/euporie/issues/25#issuecomment-1479240794) shows how to fix the problem:

>This looks like your ipykernel install is probably a bit broken. Try:
>
>    Re-installing or updating ipykernel:
>
>    ```
>    pip install --upgrade ipykernel
>    ```
>
>    Re-registering the ipython kernel:
>
>    ```
>    python -m ipykernel install --user
>    ```

**Comment by joouha** [comment] 2023-05-24 08:16
There seem to be quite a few people encountering this - I'm wondering whether when euporie is installed in a virtual environment, the default `ipykernel` kernelspec means that the kernel gets launched from inside euporie's virtalenv, which fails.

I'll do some testing

**Comment by joouha** [comment] 2023-05-24 14:48
I think this is caused by an issue in `jupyter_client` (although it can be worked-around using the steps above). I've reported it upstream.

**Comment by 875d** [comment] 2023-05-26 03:19
> [This closed issue](https://github.com/joouha/euporie/issues/25#issuecomment-1479240794) shows how to fix the problem:
> 
> > This looks like your ipykernel install is probably a bit broken. Try:
> > Re-installing or updating ipykernel:
> > ```
> > pip install --upgrade ipykernel
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Re-registering the ipython kernel:
> > ```
> > python -m ipykernel install --user
> > ```

I had this problem and these steps fixed it.

I think they should be put in the install instructions in the README until the issue is fixed.

**Comment by joouha** [comment] 2023-05-26 08:32
> I think they should be put in the install instructions in the README until the issue is fixed.

This is a good idea - I'll add something

**Closed** 2023-07-25 20:07 UTC
